#!/bin/bash
set -e

# Creacion de la BD de datastore
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $POSTGRES_ENV_POSTUSER_DATASTORE;
    CREATE DATABASE $POSTGRES_ENV_DATABASE_DATASTORE;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_ENV_POSTUSER_DATASTORE: TO $POSTGRES_ENV_DATABASE_DATASTORE;
EOSQL