#!/bin/bash
set -e

# Creacion de la BD de datastore
if [ "$POSTGRES_USER" != "$USER_DATASTORE" ]; then
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d $POSTGRES_DB <<-EOSQL
        CREATE USER $USER_DATASTORE WITH PASSWORD '$USER_DATASTORE_PWD';
        CREATE USER $USER_DATASTORE_READ WITH PASSWORD '$USER_DATASTORE_PWD';
        CREATE DATABASE $DATABASE_DATASTORE;
        GRANT ALL PRIVILEGES ON DATABASE $DATABASE_DATASTORE TO $USER_DATASTORE;
        GRANT SELECT ON ALL TABLES IN SCHEMA public TO $USER_DATASTORE_READ;
EOSQL
else
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d $POSTGRES_DB <<-EOSQL
        CREATE DATABASE $DATABASE_DATASTORE;
        GRANT ALL PRIVILEGES ON DATABASE $DATABASE_DATASTORE TO $USER_DATASTORE;
EOSQL
fi
